import './globals.css';
import { ReactNode } from 'react';
import Script from 'next/script';

export const metadata = {
  title: 'OROVE',
  description: 'Generated by create next app',
  icons: {
    icon: "/orove-logo2.png", // <-- your logo here
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* Razorpay script */}
        <Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="beforeInteractive" />
      </head>
      <body>{children}</body>
    </html>
  );
}
